### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by omrisim210** [MarkM-dev/Twitch-Previews#1]
Are there any plans for one?

How much work would that be?

zoilL

**Comment by MarkM-dev** [comment]
Hi,

No plans at the moment, it 'kinda' works on firefox but there are some breakpoints that need to be handled to support firefox fully and it would be difficult (time consuming) for me to continue and maintain both versions if twitch change anything in their design (which already seems to be somewhat different between chrome and firefox).
plus it doesn't seem to be popping off that much on chrome (175 users atm) so it doesn't seem to be worth it right now.

Maybe sometime in the future :)

Mark,

**Comment by MarkM-dev** [comment]
Twitch Previews is available for Firefox here:
https://addons.mozilla.org/en-US/firefox/addon/twitchpreviews/
