### ISSUE TITLE
Twitch Previews doesn't show preview of the new appeared streams over time. Firefox 92.0 (64-bit)

### ISSUE THREAD

**Issue by iG8R** [MarkM-dev/Twitch-Previews#10]
Hi.
The topic says by itself.
Twitch Previews — 1.9.8.1
Firefox 92.0 (64-bit)
Windows 10 (20H2 19042.1165)
Best regards,
Igor.

**Comment by MarkM-dev** [comment]
Hi,
a few questions:
1. does this happen only for hovering the followed channels or the recommended channels list? or both?
2. does this happen all the time or just sometimes?
3. do you have the favorite list feature enabled?

**Comment by iG8R** [comment]
Thanks for such a quick reply.
1. both.
2. this happens over time after the new active channels appear. Only opening Twitch Previews options window and turning off and then on Sidebar Previews helps.
3. Sidebar Favorite Channels is off.
Such behavior of Twitch Previews started about 7-10 days ago also in the previous Firefox versions — 91.0, 91.0.2

**Comment by MarkM-dev** [comment]
i'll have a look at it and see what's going on.

last question:
when it doesn't show previews when hovering on newly appeared channels, try switching to a different tab and then switching back to the tab after a second. then wait something like 2-3 seconds (just to be sure) and then try to hover the new channels. does it show the previews now? or is it still not working on the new channels?

**Comment by iG8R** [comment]
> does it show the previews now?
It doesn't, only after switching off/on Sidebar Previews it starts showing previews.

**Comment by MarkM-dev** [comment]
that's very strange then, switching tabs goes to the same function that sets the hover listeners on the channels as turning the feature on/off.
the extension should run fine with other extensions as long as they don't change certain base things in the twitch layout. maybe another extension you use change something in the sidebar as of some time ago?

**Comment by iG8R** [comment]
One more question.
Is there any way to deal with the following?
![image](https://user-images.githubusercontent.com/11407417/134049553-d59abb66-5291-4604-a9a2-03717b6b26a5.png)

**Comment by MarkM-dev** [comment]
yes, there is, iv'e been playing around with going around it recently and it is possible but it's a bit heavy on performance, ill implement it in future releases possibly if i find a good way for it to perform well.

**Comment by iG8R** [comment]
> maybe another extension you use change something in the sidebar as of some time ago?

My Add-ons list didn't change long-long time. I always used FrankerFaceZ and about half a year ago added Twitch Previews. The issue appeared only 7-10 ago. To the point, the same Add-ons (Extentions) I use in Chrome and there everything is OK.

**Comment by iG8R** [comment]
> yes, there is, iv'e been playing around with going around it recently and it is possible but it's a bit heavy on performance, ill implement it in future releases possibly if i find a good way for it to perform well.

Oh, many thanks. I thought only I had this issue.

**Comment by MarkM-dev** [comment]
> > maybe another extension you use change something in the sidebar as of some time ago?
> 
> My Add-ons list didn't change long-long time. I always used FrankerFaceZ and about half a year ago added Twitch Previews. The issue appeared only 7-10 ago. To the point, the same Add-ons (Extentions) I use in Chrome and there everything is OK.

i meant maybe they changed something in their implementation of how they do things.
maybe you can try disabling them to test? (if switching tabs fixes it) - don't forget to refresh after disabling.
also, this might be related: https://github.com/MarkM-dev/Twitch-Previews/issues/7
this seems similar and was fixed according to what he said.

**Comment by iG8R** [comment]
> also, this might be related: #7
this seems similar and was fixed according to what he said.

I mentioned above that the same Add-ons (Extentions) I use in Chrome and there everything is OK.

**Comment by MarkM-dev** [comment]
there are differences to how extensions work on different browsers, extension-wise and browser-wise.
on my firefox client (also 92.0) the extension works.. but i don't have any other extensions for twitch.

**Comment by MarkM-dev** [comment]
also when the problem happens, you can check the dev console, see if there's an error related to the extension, or maybe something with the filename "core.js".

**Comment by iG8R** [comment]
> always refresh the page (twitch) after toggling extensions on or off

After refreshing (F5) of the twitch page, Twitch Previews begins functioning OK without necessity of toggling extensions off and on.

**Comment by iG8R** [comment]
> also when the problem happens, you can check the dev console, see if there's an error related to the extension, or maybe something with the filename "core.js".

OK, thanks, I'll try.

**Comment by MarkM-dev** [comment]
> > always refresh the page (twitch) after toggling extensions on or off
> 
> After refreshing (F5) of the twitch page, Twitch Previews begins functioning OK without necessity of toggling extensions off and on.

when refreshing the page, the extensions also reload with the page, so refreshing the page after toggling extensions on or off, in this context, is to start a fresh page and only load the enabled extensions.
