### ISSUE TITLE
For some reason I can't change the Preview Size of Twitch previews anymore [Edge]

### ISSUE THREAD

**Issue by jaylay99** [MarkM-dev/Twitch-Previews#12]
It used to work but now it doesn't. I tried reinstalling the app but didn't do anything

This is on Microsoft Edge with chrome extensions

**Comment by MarkM-dev** [comment]
Hi,

I just tested this on edge and it works here.. my edge version is: Version 93.0.961.52.
try restarting the browser or checking if there's an update.
if it still doesn't work, can you check the dev console and see if there's an error related to the extension or maybe something with the file name "core.js"?
