### ISSUE TITLE
auto prediction is not working

### ISSUE THREAD

**Issue by chumtower** [MarkM-dev/Twitch-Previews#15]
I set the prediction and activated it, but is doesn't work

**Comment by MarkM-dev** [comment]
Hi,
there was an update today, it's possible that your extension got updated in the background.
refresh your twitch tabs and it should work if indeed that is the case.

please report back if the issue is fixed or not.

**Comment by MarkM-dev** [comment]
closing the issue since there was no response from op for over a week and the feature seems to work.
please reopen if the issue persists.
