### ISSUE TITLE
Enlarge Directory Previews on hover (also add image/video toggle in settings)

### ISSUE THREAD

**Issue by whoizit** [MarkM-dev/Twitch-Previews#16]
In Directory Preview I expect it to enlarge the thumbnail when hovering the mouse, same as Sidebar Previews works with same Preview Size, instead it tries to load a video preview

**Comment by MarkM-dev** [comment]
well the directory previews is designed to show live video preview since we already have the thumbnail.

i'll look into how i can fit your request to enlarge the element and show either image or video preview according to a setting for future versions.

**Comment by MarkM-dev** [comment]
well the directory previews is designed to show live video preview since we already have the thumbnail.

you want it to only enlarge the thumbnail element when you hover?

**Comment by whoizit** [comment]
I've expect same behavior as Sidebar Preview. If I inside game directory and mouse hover on stream - nothing happens, but I expect zooming as Sidebar Preview behavior

**Comment by whoizit** [comment]
for me enough only enlarge thumbnail element when I hover, yes

**Comment by MarkM-dev** [comment]
ok i understand now.
i'll look into it for the next versions.

**Comment by MarkM-dev** [comment]
Added the option to enlarge the player on speaker button click because adding element modifications on hover would be heavy in that page.
