### ISSUE TITLE
Twitch overlay extensions have a conflict with "Seek Streams Using Keyboard Arrow Keys"

### ISSUE THREAD

**Issue by jaylay99** [MarkM-dev/Twitch-Previews#17]
I'm refering to the Twitch extensions that the streamers enable on their stream, not other browsers extensions. For example, the Path of Exile extension that allows us to see the streamer's builds makes me unable to use left and right arrow keys to go forward or backward in the stream, I have to disable the Twitch extension to make it work. 

I have no idea if any other extension messes with the feature.

**Comment by MarkM-dev** [comment]
unfortunately there is currently no fix for this since there are iframes in iframes in those overlays that don't bubble the events upwards.
