### ISSUE TITLE
Sync/export settings, favorites, etc.

### ISSUE THREAD

**Issue by brw** [MarkM-dev/Twitch-Previews#18]
I'm primarily requesting this because having to re-favorite a bunch of streamers after reinstalling gets a bit annoying, but having a way to sync just about everything would be nice too (same goes for dual boot or multi-machine setups and the likes).

Glancing over the code I see that you moved away from `chrome.storage.sync` in favor of `chrome.storage.local` so I assume this has already received some thought in the past. Maybe a manual export/import feature like FFZ currently has could work too (although they also have an [open issue](https://github.com/FrankerFaceZ/FrankerFaceZ/issues/1086) asking for cloud syncing).

**Comment by MarkM-dev** [comment]
added in 2.5.
