### ISSUE TITLE
slow + decoder error Firefox

### ISSUE THREAD

**Issue by Osahashi** [MarkM-dev/Twitch-Previews#2]
Very interesting add-on!

It needs ~3 sec to preview a video of a stream, is that normal? I think that way to slow, and sometimes it doesn't review anything, it only loads but nothing happens.

I get these two errors in my console when the review doesn't load:

Cannot play media. No decoders for requested formats: video/mp4; codecs="avc1.42E01E mp4a.40.2", video/mp4;codecs="vp09.00.10.08"

Cannot play media. No decoders for requested formats: video/mp4; codecs="avc1.42E01E mp4a.40.2", video/mp4;codecs="vp09.00.10.08", video/mp4;codecs="avc1.64002A mp4a.40.2", video/mp4;codecs="avc1.4D401F mp4a.40.2", video/mp4;codecs="avc1.4D401F mp4a.40.2", video/mp4;codecs="avc1.4D401F mp4a.40.2", video/mp4;codecs="avc1.4D401F mp4a.40.2", video/mp4;codecs="avc1.4D401F", video/mp4;codecs="mp4a.40.2"

**Comment by MarkM-dev** [comment]
Hi,

yes, sometimes it may take 3 seconds to load, depending on your pc and internet connection - it makes a new video element and waits for it to start playing to display it.

the error is not related to the extension but to how the browser reads the video stream - which is controlled by twitch (iframe, video and stream are controlled by twitch).
