### ISSUE TITLE
Predictions sniper breaks in the moderator view

### ISSUE THREAD

**Issue by Seb3thehacker** [MarkM-dev/Twitch-Previews#21]
The predictions sniper doesn't work when moderating a community. It tries to predict but gets stuck on this screen:
![twitcherror](https://user-images.githubusercontent.com/88462253/144526572-9755d84d-c736-49e4-af33-bc2c7afcf727.png)

A separate switch to enable/disable predictions when you are mod would be great, because I want it only predict on streams I'm not mod on.

**Comment by MarkM-dev** [comment]
yeah in the next version i'll disable predictions notifications and the sniper in the mod view, they are redundant there.
thanks for letting me know!

**Comment by Seb3thehacker** [comment]
Great!
