### ISSUE TITLE
Advanced Video Embeds not working

### ISSUE THREAD

**Issue by Vaeb** [MarkM-dev/Twitch-Previews#23]
#### Steps to reproduce:
1. Enable various Twitch-Previews settings including the Screenshot Stream Button
2. Enable the "Advanced Video Embeds" setting
3. Open a new multistre.am tab with a currently live stream (e.g. https://multistre.am/buddha/layout0/)

#### Current behaviour:
No changes occur to the embedded stream, e.g. the Screenshot Stream Button is not visible, despite changes operating fine on non-embedded streams.

#### Expected behaviour:

Changes occur to the embed relevant to the settings enabled, such as seeking and a screenshot button.

#### DevTools errors for the extension (chrome-extension://hpmbiinljekjjcjgijnlbmgcmoonclah):

![image](https://user-images.githubusercontent.com/28259440/145275925-afc27f2a-5e17-43c9-bfaa-5dd3695e7972.png)

#### Other (relevant) extensions enabled:
- FrankerFaceZ: Adds features to stream embeds, such as an Audio Compressor button.

#### Environment:
- Twitch Previews v2.7
- Google Chrome 96.0.4664.93 (Official Build) (64-bit)
- Windows PC

**Comment by MarkM-dev** [comment]
yep the Advances Video Embeds feature is intended for use in the Twitch Previews Multi-Stream and the video embeds that you start from the sidebar.
all the features in the extension are intended for use in Twitch and not in external sites.

You can use the Twitch Previews Multi-Stream feature by clicking the button under the stream:
![1](https://user-images.githubusercontent.com/38380938/145277936-c360d486-1c0d-4d22-b6a8-0267a7de2268.JPG)

Then you can use the top search bar to add streams (video embeds) and click the same button in the top bar search results.
And you can also add video embeds on the fly using the button in the sidebar under the view count (currently when in video preview mode, will be enabled for Image preview mode as well soon):
![11](https://user-images.githubusercontent.com/38380938/145278651-0a16dab2-a971-461a-aec3-9a7ccf19f24a.JPG)

Also, in the Multi-Stream page, there is a layout preset button on the left of the top search bar where you can choose from 3 default layout presets or make one on your own and save it as a preset.

**Comment by Vaeb** [comment]
Ah I see, thank you for the clarification.

Then could I pivot this into requesting either the feature functionality to work on other embed sites, or clarification in the description that it's only for in-house multistreams? The former should be possible given that FFZ is able to achieve it.

![image](https://user-images.githubusercontent.com/28259440/145283838-4274eddf-efc4-419f-8b5b-0a21bc86d153.png)

**Comment by MarkM-dev** [comment]
The Advanced Video Embeds feature is located directly under the Multi-Stream feature in the settings, i thought it was clear that this is in regards to the in-house Multi-Stream.
Adding support to an external multi-stream site would be an annoyance to maintain, especially since there is already a Multi-Stream feature in the extension (and a pretty good one).
