### ISSUE TITLE
[BUG] Auto Extend Sidebar

### ISSUE THREAD

**Issue by yamiM0NSTER** [MarkM-dev/Twitch-Previews#25]
**Version:** 2.9

**What is happening:**

Basically even though option is set to off, sidebar automatically extends itself. Can be seen here: https://youtu.be/glaNEfnJHbU
*Note:* Soemtimes it stops auto extending, however once you hover over online channel and preview loads, once you move your mouse it extends again.

**Expected behaviour:**

If option is set to off, it should not extend the sidebar.

**Comment by MarkM-dev** [comment]
Yep that's how it's supposed to be because you have the Favorites feature enabled.
![1](https://user-images.githubusercontent.com/38380938/147583967-921c60d6-154d-45c8-8baa-42ebed04c0c9.PNG)
![2](https://user-images.githubusercontent.com/38380938/147583970-ecd03613-0502-4c99-a151-28212f27d98e.PNG)
