### ISSUE TITLE
wrong profile pic in youtube section

### ISSUE THREAD

**Issue by TOZEDhub** [MarkM-dev/Twitch-Previews#26]
Hey. 

Great Addon. 
However, the profile picture in the youtube section is always weird. DrDisrespect always has the same as Sodapoppin. I mean, it's the animated profile picture from Soda, but I assume this isn't a 7TV issue.

Here's a gyazo of what I mean: https://gyazo.com/831fd16b63edaeeb30dfef134715d286

**Comment by MarkM-dev** [comment]
Hi, fixed in 3.2.
