### ISSUE TITLE
Auto refresh on twitch player can't refresh the player and it instead refreshes the website

### ISSUE THREAD

**Issue by Void48** [MarkM-dev/Twitch-Previews#30]
![image](https://user-images.githubusercontent.com/85196642/152255268-9e7bbfc2-5eff-4b0f-87b1-461eab027926.png)

**Comment by MarkM-dev** [comment]
on error #4000 it refreshes the page, yes.

**Comment by Void48** [comment]
> on error #4000 it refreshes the page, yes.

it shouldn't say that it refreshes the player then 👍🏻
