### ISSUE TITLE
Facebook Sidebar game category showing markup instead of text.

### ISSUE THREAD

**Issue by Mazmol** [MarkM-dev/Twitch-Previews#32]
![image](https://user-images.githubusercontent.com/38956955/152878541-8c390a4b-3de1-4457-b28a-1c5c19d801d1.png)
Adjust it so it shows what game they playing instead of this random HTML :)

**Comment by MarkM-dev** [comment]
you might be getting different data than what i'm getting, i'll look into this.
1. are you logged into facebook or no?
2. if you're not logged in, can you follow the steps here and see if it fixes it? https://github.com/MarkM-dev/Twitch-Previews/issues/33 (this will log you out so only try it if you're not logged into facebook),

thanks,

**Comment by Mazmol** [comment]
1. I am logged in this 
2. this doesn't apply.

this happened to other people also

**Comment by MarkM-dev** [comment]
yep makes sense, thanks for letting me know!
will be fixed soon.

**Comment by MarkM-dev** [comment]
Fixed in 3.4.1, update will be rolling out in a few hours to a day or two.
