### ISSUE TITLE
[FB Gaming sidebar KNOWN BUG TEMP FIX] FB Gaming sidebar sometimes not populating with streamers.

### ISSUE THREAD

**Issue by MarkM-dev** [MarkM-dev/Twitch-Previews#33]
Known issue: FB sidebar section not populating with streamers when logged out of facebook in the browser.

Temporary fix until it's handled by the extension:
Facebook stores cookies automatically, if you're logged out of facebook, sometimes there seems to be a "token expired" scenario.
To fix this, you need to clear your Facebook data from your browser:

**Chrome:** 
1. go to chrome://settings/content/all?searchSubpage=facebook
2. clear all entries related to facebook.
3. open the Twitch Previews settings menu, then open the FB streamers edit menu and click "Save" (this would force a refresh for the FB Gaming streamers list),
4. after a few seconds the list should refresh with your FB streamers.

**Firefox:**
1. go to about:preferences#privacy
2. under "Cookies and Site Data" section click on "Manage Data...".
3. in the popup search for "facebook".
4. remove all facebook related entries in the box,
5. click "Save Changes".
6. open the Twitch Previews settings menu, then open the FB streamers edit menu and click "Save" (this would force a refresh for the FB Gaming streamers list),
7. after a few seconds the list should refresh with your FB streamers.

**Other browsers:**
1. clear facebook related site data and cookies from your browser's settings.
2. open the Twitch Previews settings menu, then open the FB streamers edit menu and click "Save" (this would force a refresh for the FB Gaming streamers list),
3. after a few seconds the list should refresh with your FB streamers.

Will be fixed soon :)

**Comment by Nadabyah** [comment]
That still doesn't work on latest Firefox on Ubuntu 20.10

**Comment by MarkM-dev** [comment]
make sure you're on version 3.4.4
refresh your twitch.
make sure you copied the streamers names correctly as they are written in their Facebook URLs.
click save on the edit box to force a FB list refresh.

**Comment by Nadabyah** [comment]
> 

The latest version available for Firefox is 3.4.2..... https://imgur.com/6isq12L.png

**Comment by MarkM-dev** [comment]
it was, it's awaiting approval, should be available soon.

**Comment by MarkM-dev** [comment]
meanwhile, make sure your list looks like this:
no urls, no comma's at the end, no spaces. only the names as they are in their facebook page URL.
![Capture](https://user-images.githubusercontent.com/38380938/153419102-838e6e38-92e8-43f3-84df-ec25e9fd29ac.PNG)

**Comment by Nadabyah** [comment]
3.4.4 freshly updated. Cookies cleared. Cache cleared. Went into FB streamer names and saved... nothing hoss. Nothing.... 
![fb](https://user-images.githubusercontent.com/37978673/153518251-a60de19b-9d79-46d6-b706-f8dcd60e8c26.png)
![fb2](https://user-images.githubusercontent.com/37978673/153518339-e6fcfde0-c410-4820-911a-dbdea4ac952f.png)

**Comment by MarkM-dev** [comment]
i found an issue where the extension is triggering spam protection, working on fixing it.
can you screenshot what you see when going to a currently live streamer's page with this url:
https://mobile.facebook.com/gaming/ratedepicz/

**Comment by Nadabyah** [comment]
![fb4](https://user-images.githubusercontent.com/37978673/153519197-7bb3679e-92a3-4284-927f-dca7e37f9791.png)

**Comment by MarkM-dev** [comment]
1. does it work if you log into facebook?
2. do you have something blocking traffic to facebook (your video is not loading)?
3. did you try on a different browser?

**Comment by Nadabyah** [comment]
It loads after I remove the 'm.' before 'facebook.com'

I disabled Adguard and it still wont load with the mobile address you linked above. 

I'll try on another browser. Give me a few.

**Comment by MarkM-dev** [comment]
when you're logged in, click that save button again in the box and wait a few seconds, see if the list appears then.

**Comment by MarkM-dev** [comment]
i changed something that also might be a fix for this as-well.
turn off your FB sidebar feature in the extension, then refresh all your twitch tabs.
clear the facebook browser data again, then you can login to facebook, or not, your choice.
wait for version 3.4.5 (already available on chrome).
if you already have 3.4.5 - wait 1 hour before turning the feature back on.
then turn it on after at least 1 hour. see if it works a few seconds after turning it on. if not, click the save button again then give it a few seconds.
let me know what happens.

**Comment by MarkM-dev** [comment]
1. did you try the feature on the fresh chrome install or just try to play the video? the video doesn't matter, it's the data that is shown and it appears to be fine from the screenshot.

2. i changed something that also might be a fix for this as-well.
turn off your FB sidebar feature in the extension, then refresh all your twitch tabs.
clear the facebook browser data again, then you can login to facebook, or not, your choice.
wait for version 3.4.5 (already available on chrome), don't turn it on if you have 3.4.4 and if you just updates to 3.5.5 - wait 1 hour before turning it back on.
if you already have 3.4.5 - wait 1 hour before turning the feature back on.
then turn it on after at least 1 hour. see if it works a few seconds after turning it on. if not, click the save button again then give it a few seconds.
don't use the feature on any browser during that 1 hour.

let me know what happens.

**Comment by Nadabyah** [comment]
I've tried the feature on the new install of Chrome. Hasn't worked for me. Logged in or logged out.

Haven't done the one hour off/on thing in Chrome. 

Firefox still doesn't work either. I followed all the suggestions in #2 above and it didn't work. I wiped FB cookies to begin with after disabling the FB feature in sidebar. Waited an hour. Turned it back on. Nothing worked after an hour. 

I then repeated the process logged into FB with the whole one hour off/on deal. Nothing worked.

Let me know if you need anymore troubleshooting from me on my end.

**Comment by MarkM-dev** [comment]
i tested the issue on a linux machine, apparently there is an issue only with linux devices and the facebook feature at the moment.
i'll issue a fix sometime soon.

**Comment by Nadabyah** [comment]
No rush

**Comment by MarkM-dev** [comment]
should be fixed in 3.4.7 (just came out), let me know how it goes.
you might need to click save on the edit box again if it shows "no live streamers" after approving the new permissions (if someone is actually live).

**Comment by Nadabyah** [comment]
Great job hoss. Thanks for the fix. Works great. 
![FBfixed](https://user-images.githubusercontent.com/37978673/154750103-2d45f2c3-151c-4583-8d6b-cef4d830ed22.png)
