### ISSUE TITLE
[bug] Preview  and Account changing.

### ISSUE THREAD

**Issue by Mazmol** [MarkM-dev/Twitch-Previews#34]
![image](https://user-images.githubusercontent.com/38956955/152905196-9af6bc7c-38ba-4b47-8ca3-85968ac9ad1e.png) - Signed in also this was done using the purple square 

![image](https://user-images.githubusercontent.com/38956955/152905729-18a2c606-6ac5-46b3-8a85-18e36d5cd1f7.png)

Account : One thing though, You can't use a gaming page as the profile, you need to be logged into your main fb account for it to come up on the twitch feed.

**Comment by MarkM-dev** [comment]
make sure you're on version 3.4.1 (already out, you can update manually at chrome://extensions/ click the UPDATE button and then refresh your twitch tabs).
let me know if something still isn't working after you update.

**Comment by MarkM-dev** [comment]
also, if you're logged out of facebook, please refer to this: https://github.com/MarkM-dev/Twitch-Previews/issues/33
it should fix the issue for now until i automate this or think of a way to do this differently.

**Comment by MarkM-dev** [comment]
apparently the bug is related to the preview mode you're in, switch to video preview mode on the right side of the settings until i issue a fix for this.

**Comment by MarkM-dev** [comment]
these issues have been fixed in 3.4.2. will be available soon.
