### ISSUE TITLE
Not Adding Stream

### ISSUE THREAD

**Issue by vloted** [MarkM-dev/Twitch-Previews#35]
When I try and add a FB streamer it doesn't show on the side bar. It says, "No live FB Gaming streamers" even when they are live.

**Comment by MarkM-dev** [comment]
are you logged into facebook?
if not, refer to this to fix it: https://github.com/MarkM-dev/Twitch-Previews/issues/33

**Comment by MarkM-dev** [comment]
things should work now in 3.4.2, make sure your extension is updated.
