### ISSUE TITLE
Enhancement // Show streams from every platform under just one section

### ISSUE THREAD

**Issue by MESSIOS** [MarkM-dev/Twitch-Previews#37]
I would like it if every stream from the different platforms would just be displayed under the followed section. So that there are no gaps (see screenshot) and the streamers are simply sorted by audience. Maybe you can add a small icon next to the name that indicated what platform the streamer is using..

![chrome_pm5g9yHGXM](https://user-images.githubusercontent.com/67313723/153278119-4589186a-2d78-4f30-9d1f-42ae5c5f317b.png)

![chrome_rBMhgGmiPg](https://user-images.githubusercontent.com/67313723/153278147-80e02cd4-8382-4fa4-b979-72b84ad64040.png)
.

**Comment by MarkM-dev** [comment]
in the next version you wont have any gaps anymore :)
putting them all under the followed section is currently not recommended since it might make the sidebar unstable.
