### ISSUE TITLE
Youtube channels in sidebar not showing

### ISSUE THREAD

**Issue by ptrcklawrence** [MarkM-dev/Twitch-Previews#39]
All of my subscribe youtube channels aren't showing in my sidebar. It only shows 3-5 youtube channels, but when I opened my youtube, there's a couple more, even gaming channels that are live aren't showing.

**Comment by ptrcklawrence** [comment]
This what I see on my twitch as of the moment
![1](https://user-images.githubusercontent.com/91199801/153965742-f2c29641-74b9-4a62-b420-7856be41e24d.png)

and these are channels that are live on my youtube right now
![2](https://user-images.githubusercontent.com/91199801/153965859-9d169502-b452-481a-b149-7bf50a51a3d2.png)

there are also rare instances that some channels are duplicated on my sidebar

**Comment by klober31** [comment]
Hi, so the duplicate seems to be the same channel but with different content, it's possible to do on YouTube, you can see that the title below the stream name is different.
As for the channels that do not appear, did you notice if it only happens with 24 hours live channels? 
it seems to me that some channels appear live on YouTube side bar (like the screenshot you sent), but they do not appear in the subscriptions page: https://www.youtube.com/feed/subscriptions

**Comment by MarkM-dev** [comment]
the extension fetches streams from youtube after they have been filtered by youtube.
it seems that youtube filters 24/7 channels and other certain categories.
in the future, i'll add an option to manually add streamers to the youtube sidebar.
