### ISSUE TITLE
Auto refresh not following up on persistent errors if they happen immediately after the first one.

### ISSUE THREAD

**Issue by Martian746** [MarkM-dev/Twitch-Previews#4]
* macOS: Catalina 10.15.7
* Chrome: 89.0.4389.114
* Twitch Previews: 1.7.1.0

![image](https://user-images.githubusercontent.com/60570225/114647572-e65f2f00-9d0f-11eb-8502-5a6d7879c063.png)

![image](https://user-images.githubusercontent.com/60570225/114647400-9e400c80-9d0f-11eb-9a2f-86ea5fae9d50.png)

1. `Auto refresh on twitch player error` in Twitch Previews was turned on before the Twitch tab was created.
2. When the #2000 error shows up in the Twitch tab, the Chrome window was on the second monitor, and was not the active window, but the Twitch tab (#2000) in Chrome was the active tab.
3. The Twitch tab didn't automatically refresh.
4. When I click on the Twitch player — not on the `Click Here to Reload Player` button or any link, just to make the Chrome window become the active window to test — it still doesn't refresh.

I'm also using BetterTTV 7.2.92, if it matters.

**Comment by MarkM-dev** [comment]
Hi,

everything works for me (win 10)..
is this the only time it hasn't worked or does the feature never work for you?

you can test the feature in a twitch tab with a stream running by running the following command in your chrome dev console:

`document.querySelector(".video-player").querySelector('video').load()`

this will cause a #4000 error and twitch previews should make a full page refresh for error #4000 (i know you got a #2000, its the same, code wise).

did the page refresh? 
if it did - then the feature works and for some reason it didn't register an error listener that time you got the error.

note:
in errors #1000 and #2000, twitch previews will attempt to programmatically click the red "Click Here to Reload Player" button if it exists - if not, it will make a full page refresh, make sure you don't have some security policy or extension that prevents programmatic actions (like clicks) from custom sources or something like that (i.e extensions etc.).

also, make sure that the line of code above is actually pointing to the main twitch player, if not - you might have another extension that is creating another twitch player with the same classes as the official main twitch player.

let me know what happens.

**Comment by Martian746** [comment]
Thank you for the explanation.

I have little experience using this extension at the time I created this issue. I was more like listening to Twitch, on the second monitor, when I'm working on something else. While the Twitch tab is the active tab, the seperate Chrome window contains it is not the active window. I just quite often found that the Twitch tab ended up with #2000 error, although `Auto refresh on twitch player error` in Twitch Previews was turned on.

First, `Auto refresh on twitch player error` works for sure, in general. As I tried `document.querySelector(".video-player").querySelector('video').load()` in chrome dev console and it refreshes automatically.

But, it also didn't refreshing in a special case. The #2000 error happened, Twitch-Previews refreshed the tab immediately but the stream failed reloading after few seconds, it ended up with another #2000 error. Twitch-Previews would not refresh the tab for the second time. The tab would remains showing #2000 error afterwards until someone manually refresh the page or "Click Here to Reload Player".

This case can be easily reproduced by turn off network or just unplug the network cable. 

So I guess this is why I found auto refresh 'not working', it's actually my network was down for a while, Twitch-Previews auto freshed for the first time, but not the second time.

**Comment by MarkM-dev** [comment]
yep i see your point, i'll have a look at it when i get a chance.

also, twitch implemented a scenario where if the tab (or window) with the player is not active (meaning you are currently not focused on the player - or in twitch's terms: "you're not watching the stream") the video will not start playing until you come back to it so unfortunately it's probably not going to refresh a window that's opened on a different screen and not focused.

**Comment by MarkM-dev** [comment]
Fixed, 5 seconds after a refresh it will check if another refresh is needed and will continue checking every 5 seconds as long as there is an error.
Will be available next version.
