### ISSUE TITLE
Twitch API V5

### ISSUE THREAD

**Issue by LizzieA69** [MarkM-dev/Twitch-Previews#42]
Were you aware that the Twitch API V5 is now legacy and will be shutdown on February, 28, 2022? Will this extension be upgraded to work with the new Twitch API? The info about the V5 API shuting down is in the Twitch blog located here: https://blog.twitch.tv/de-de/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/

**Comment by MarkM-dev** [comment]
don't worry about it.
