### ISSUE TITLE
[Feature request] Hide reruns

### ISSUE THREAD

**Issue by janisdaugavietisd** [MarkM-dev/Twitch-Previews#43]
Love the extension.
Give us an option to hide reruns. Rerun is when streamer replays the past stream. It clogs up interface and is annoying but Twitch doesn't allow us to hide it.
It looks like this-> https://i.imgur.com/TvUyuAE.jpeg

**Comment by MarkM-dev** [comment]
Glad you like the extension :)
Hiding reruns seems like a feature that would more likely clutter the extension rather than be useful since reruns are not very common and when they do happen it's only 1 or 2 streamers.
So the feature will not be added.
But thanks for suggesting :)
