### ISSUE TITLE
youtube sidebar isnt refreshing/updating

### ISSUE THREAD

**Issue by lainadloshi** [MarkM-dev/Twitch-Previews#44]
![image](https://user-images.githubusercontent.com/100100850/154870464-d1d0a4f1-6756-4fb9-b091-eef407f877e8.png)

Just notice it like a day or 2. My sidebar for my youtube channels is not being updated and being spammed with one channel. not sure how to go about fixing it.

**Comment by MarkM-dev** [comment]
what extension version are you on?

**Comment by MarkM-dev** [comment]
released a new version just now (v3.4.8), should be fixed.
