### ISSUE TITLE
Using Twitch Previews with Alternate Twitch Player

### ISSUE THREAD

**Issue by K31X** [MarkM-dev/Twitch-Previews#46]
Hello,
first of all I just found your addon today and  I like it alot especially about the auto prediction bot.

For years I use the chrome addon "Twitch alternate player" and its really good and smooth for my Computer.
Unfortunately your addon is not active when I have the twitch alternate player on.
You would be my hero if you can fix that.

here is the alternate player I was talking about: https://chrome.google.com/webstore/detail/alternate-player-for-twit/bhplkbgoehhhddaoolmakpocnenplmhf

thank you for providing such a nice tool.

**Comment by MarkM-dev** [comment]
Hey glad you like it and thanks for the compliments!

unfortunately i cannot add additional support to a different extension of this kind since it would make it really difficult to maintain as changes occur throughout twitch and also other extensions like these.
