### ISSUE TITLE
Video preview not loading on Edge

### ISSUE THREAD

**Issue by DevonRumbold** [MarkM-dev/Twitch-Previews#47]
The video preview function doesn't seem to be functional in the Microsoft Edge browser. It gets stuck at "loading stream...", not even loading the multi-stream or volume icons. I've turned down the resolution to 300px, turned off advanced imbeds, and other potential memory saves, but it still won't load even after 10 minutes.

**Comment by MarkM-dev** [comment]
Hi,

seems to be working on my end.
try disabling ALL other extensions, then refresh the page. see if it works. if it starts working, enable other extensions one by one (refresh twitch after every enable) to find the culprit.

there might be another thing where you need to go to the channel first to accept the age restriction screen if a streamer has set their channel as age restricted.

**Comment by MarkM-dev** [comment]
seems to be working on my end.
try disabling ALL other extensions, then refresh the page. see if it works. if it starts working, enable other extensions one by one (refresh twitch after every enable) to find the culprit.

there might be another thing where you need to go to the channel first to accept the age restriction screen if a streamer has set their channel as age restricted.

**Comment by DevonRumbold** [comment]
I've tried disabling all extensions and extra setting in the twitch previews window, still doesn't load. I've used the same combination of extensions in both chrome and brave browsers just fine anyway. Also I've already authenticated/accepted age restriction on all the channels that I watch already.

The only other thing I can think of is that I copied my entire user data folder from brave to edge when moving over so maybe there's some extra junk in there interfering with the extension somehow? Though everything else works just fine.

**Comment by DevonRumbold** [comment]
Additionally, twitch preview doesn't seem to appear in the task manager alongside my other extensions, though the subframe does show up in the task manager when mousing over streams in the side column.

**Comment by MarkM-dev** [comment]
is there anything in the console when you try to preview?

the task manager only shows the background script activity which is not active when it's not needed.

**Comment by DevonRumbold** [comment]
Ah, unfortunately I don't know how to use the windows console.

**Comment by MarkM-dev** [comment]
F12 in the twitch tab then go to the console tab.
hover the mouse over a streamer and see if there are errors that show up in the console related to the extension.

**Comment by DevonRumbold** [comment]
This is what I get:
![Screenshot 2022-03-06 170356](https://user-images.githubusercontent.com/46904056/156944067-7e4f4b3e-8bd7-4064-8e36-b6ca91acd52f.png)

**Comment by MarkM-dev** [comment]
those are not related to the extension.
can you try installing the extension on another browser (a clean one without extensions on it) and see if it works then?

**Comment by DevonRumbold** [comment]
This is what I get when I use it in a clean copy of Brave. Though the video preview actually loads there.
![Screenshot 2022-03-06 172605](https://user-images.githubusercontent.com/46904056/156944694-9a7a42d3-732b-4646-92ac-a14aa6afe081.png)

**Comment by DevonRumbold** [comment]
Okay, I tried Edge again and cleared everything but what appears when I mouse over
![Screenshot 2022-03-06 173348](https://user-images.githubusercontent.com/46904056/156944980-bf3c4585-0fb7-42be-b008-d857cd78c2b4.png)

**Comment by MarkM-dev** [comment]
the errors on brave are unrelated to the extension.
i think there is something in your edge that is causing this since it works on another browser.
try uninstalling and reinstalling the extension maybe.

**Comment by DevonRumbold** [comment]
I've already uninstalled and reinstalled. Even tried both from the Chrome and Microsoft stores.

**Comment by MarkM-dev** [comment]
what does it says when you expand that "got message from unexpected source" error?

**Comment by DevonRumbold** [comment]
Not much.
![Screenshot 2022-03-06 184007](https://user-images.githubusercontent.com/46904056/156947326-f08ee3e3-8a33-460c-8cdf-5c61cae13794.png)

**Comment by MarkM-dev** [comment]
sorry but it seems that there is an issue with either your edge specifically, or twitch changed things for certain visitors and i don't have a way of debugging it. MOAT is an Oracle analytics tools btw.
you can try clearing all your twitch cookies (find how to online) and localstorage (go to twitch and enter this in the console: "localStorage.clear()" - without quotations), refresh the page and then log back in but there's nothing i can do beyond this. we wait until they fix this, if indeed it's a problem on their end. or maybe they are trying to block the feature for some reason, but i doubt that.
