### ISSUE TITLE
[Request] FB & YouTube list under Twitch Followed

### ISSUE THREAD

**Issue by AmpRoleplay** [MarkM-dev/Twitch-Previews#49]
Hey, love the extension, would it be possible to get the FB & YouTube followed channels list to show underneath the Twitch Followed list? 

I mainly go to Twitch to watch twitch streamers but also like to see if the 2-3 people that are on FB are streaming, but everything I go to twitch and go to click on a Twitch streamer, the FB & YouTube list decide to finally load and pushes the Twitch list down causing me to click another streamer instead.

Thanks.

**Comment by MarkM-dev** [comment]
currently rearranging the lists is not possible, might add it in the future but not currently.
the facebook and youtube lists may take a few seconds to load at first, but after the first time it should not disturb too much.

when you go to a twitch tab, it checks if enough time passed for a refresh, if it has, it will refresh and may take a few seconds and update the sidebar if needed. this is probably what you are talking about.
sidebar updates also occur when the twitch lists get updated.

as development continues (this is a "weekend project"), the features will get better. but for now it's what we got :)
