### ISSUE TITLE
Add an option to auto expand Recommended channels section.

### ISSUE THREAD

**Issue by Fujosej** [MarkM-dev/Twitch-Previews#5]
Can you add an option similar to this
![image](https://user-images.githubusercontent.com/37980944/122221331-dc95ab80-ceb9-11eb-8419-2ff76e3bf1cd.png)

but for Recommended channels
![image](https://user-images.githubusercontent.com/37980944/122221487-fc2cd400-ceb9-11eb-89e8-59b6804a3bde.png)

Thanks! Really dig follower preview feature
![image](https://user-images.githubusercontent.com/37980944/122221858-5c237a80-ceba-11eb-82e9-e6dc473489e1.png)

**Comment by MarkM-dev** [comment]
Added to default functionality of the extend sidebar feature.
Will be available next version.
