### ISSUE TITLE
[Feature Request] A real clip download button

### ISSUE THREAD

**Issue by Velegand** [MarkM-dev/Twitch-Previews#53]
The current download button seems to just create an mp4 file thats code is just a link to the mp4 file stored on Twitch.
Maybe there could be an option whether to actually download the mp4 or the weird link file that it currently creates.

**Comment by MarkM-dev** [comment]
The clips are downloaded when i click the button on my end.
what is your OS, OS version, browser, browser version?

**Comment by MarkM-dev** [comment]
oh i see... has this always been like this? i don't remember it like this when i made the feature (i personally don't use the feature).
ill think of something thanks for letting me know!

**Comment by MarkM-dev** [comment]
Fixed in 3.5.6.
If the video appears in a new tab instead of downloading, right-click the video in the new tab and then save.
