### ISSUE TITLE
Arrow keys in chat interacting with player

### ISSUE THREAD

**Issue by Clayrok** [MarkM-dev/Twitch-Previews#54]
Pressing Left/Right arrow keys while writing in the chat makes the stream jump 5 seconds forward/backward when Seeking is enabled.
The Seeking should be disabled when the chat message input is focused.

**Comment by MarkM-dev** [comment]
it works fine on my end.
what is your OS, OS version, browser, browser version?

**Comment by Clayrok** [comment]
I'm on windows 11.
I use Brave version 1.36.119.
I tried to disable every other extensions to test and the bug still occurs.

**Comment by MarkM-dev** [comment]
ok thanks for letting me know, there might have been a change in twitch ui a while ago that caused this. ill think of a way to debug this soon.

**Comment by MarkM-dev** [comment]
can you two test something?

1. make sure the bug is still happening.
2. then open the dev console (F12).
3. in the Console tab enter this:
`document.body.addEventListener('keydown', function(event) {
    console.log(event.target);
})`
4. press Enter.
5. go to the chat and press the left or right arrow.
6. screenshot what appears in the console.

**Comment by Clayrok** [comment]
Here's what I get

![image](https://user-images.githubusercontent.com/48133135/160479568-a6c7baba-639f-4e47-8ed3-66028fd71fd8.png)

**Comment by MarkM-dev** [comment]
nice, this helps! (the ui is different than mine).
would you mind doing the same for the top search bar?

**Comment by Clayrok** [comment]
I don't have the bug in the top search bar.
Here's what I get
![image](https://user-images.githubusercontent.com/48133135/160484886-ceeba1bb-dd2c-4026-84c1-a90d2014be9b.png)

**Comment by MarkM-dev** [comment]
ok thanks, ill update extension in the next few days.

**Comment by Clayrok** [comment]
I disabled BetterTTV before sending you the screenshots because I get different results with this extension enabled (I still get the bug in the chat).
Here's what I get in the chat with BetterTTV:
![image](https://user-images.githubusercontent.com/48133135/160485940-b578af2e-b00f-46e6-9a59-3e8a75a3576f.png)

And here's what I get in the top search bar with BetterTTV:
![image](https://user-images.githubusercontent.com/48133135/160485822-ff690031-bd28-4b2f-8642-e5075b1c011c.png)

**Comment by Clayrok** [comment]
My bad, the results look similar but the script name is different

**Comment by MarkM-dev** [comment]
yeah it's the same all good.

**Comment by electriceccentric** [comment]
This is what I get for the chat box:

![Screenshot 2022-03-28 193459](https://user-images.githubusercontent.com/20360229/160509743-2969fd62-2f39-4663-8f03-3322f6a19de2.png)

And this is for the top search box:

![Screenshot 2022-03-28 202904](https://user-images.githubusercontent.com/20360229/160514310-13368386-daad-401d-a9b1-a14bf55162b3.png)

**Comment by MarkM-dev** [comment]
fixed in 3.5.6.
let me know if it's fixed or not when you get the update.

**Comment by Clayrok** [comment]
It's fixed, thank you very much for your hard work

**Comment by electriceccentric** [comment]
Thanks for the speedy fix! I'm very grateful everything works perfectly now!
