### ISSUE TITLE
[Bug/Feature request] Streamers below in the "Show more" list aren't affect by T-P

### ISSUE THREAD

**Issue by RedSnt** [MarkM-dev/Twitch-Previews#58]
![vivaldi_w7VVn3o7h1](https://user-images.githubusercontent.com/6242718/166661911-98a451c9-6e5d-496f-9105-cb8317ac5f01.gif)

What I'm trying to show here is that one cannot drag streams in that are loaded "late". I assume it has to do with T-P loading in after the initial page load, and doesn't affect stuff appended to the page after it's initial load.  
So I'm just wondering if it would be possible for T-P to work on those?  
Maybe not worth looking into as it's a handful of streams?  

Anyway, love the extension, this is just an ❗ awareness note.

**Comment by MarkM-dev** [comment]
Hi,
glad you like the extension!

does this happen every time you click the show more or sometimes?
- you can turn on the auto extend sidebar feature (it should always work this way, though sidebar will have you be opened for the "show more" button to be exposed).
- a way to resolve a lot of issues that seem to not work temporarily is to switch to a different tab and then switch back to the twitch tab and it fixes anything that seems to not work.

**Comment by RedSnt** [comment]
Thanks for the help, yep, setting the sidebar to autoexpand solved this issue 👍
It happened every time, and switching tabs back and forth didn't solve the issue.
