### ISSUE TITLE
Video previews adds entries to browser history

### ISSUE THREAD

**Issue by Pixelz** [MarkM-dev/Twitch-Previews#6]
On chromium (I assume this also happens on Chrome), with video previews on, a new entry is added to the browser history each time you hover over a stream in the navigation sidebar. With image previews this doesn't happen.

Right-clicking on the back-button after hovering over a few channels right after switching from one stream to another:
![image](https://user-images.githubusercontent.com/222720/125149892-09955100-e13c-11eb-92f0-5f359a1e286a.png)

**Comment by MarkM-dev** [comment]
Welp, the history belongs to the user and cannot be removed so there's nothing i can do about it.. i guess twitch does that when their iframe is created.
on the other hand, if you talk on discord using MOUSE4, the page wont navigate back if you accidently use the push to talk while having the mouse in the browser :)
