### ISSUE TITLE
Buttons on all players tab in twitch previews are not showing in Firefox version.

### ISSUE THREAD

**Issue by page438** [MarkM-dev/Twitch-Previews#60]
In the Firefox version, the button on the All Players tab in the twitch previews at the bottom of the broadcast screen is not displayed.
![Screenshot 2022-05-09 at 08-59-45 고세구___ - Twitch](https://user-images.githubusercontent.com/105179423/167321313-824e04a6-a44a-4d81-bcee-15f0574890ec.png)

**Comment by MarkM-dev** [comment]
Fixed in 3.5.8. will be available on firefox version soon.
