### ISSUE TITLE
[Bug/Feature request] 7TV emotes in Mulit/Custom Chats

### ISSUE THREAD

**Issue by HukilauKohi** [MarkM-dev/Twitch-Previews#62]
Love the extension.  I almost exclusively watch Twitch using Multi-Stream and Multi-Chat now, and can't imagine going back.

My only complaint is that I cannot see 7TV emotes in my Multi-Chat, as shown in the comparison below.  I don't think any of my other extension or settings should be blocking them.

![Twitch Chat 7TV](https://user-images.githubusercontent.com/105951275/169618805-20c9ecba-dd2e-4aef-acac-00c4ea73fac6.png)
Custom/Multi-Chat without 7TH emotes on the Left, normal Twitch chat with 7TV emotes on the right

**Comment by MarkM-dev** [comment]
Hi,
Thanks for the compliments, i myself also can't imagine twitch without it lol
This is more of a 7TV thing, you would have to ask them to add support to twitch's chat embeds.
Example link that the extension uses for chat embeds:
https://www.twitch.tv/embed/greekgodx/chat?darkpopout&parent=twitch.tv
