### ISSUE TITLE
preview size slider issue

### ISSUE THREAD

**Issue by manisingh9** [MarkM-dev/Twitch-Previews#63]
Preview size slider of video show and image show not working, i cannot increase or decrease it.

**Comment by MarkM-dev** [comment]
try disabling other extensions that you have, there have been some reports of a certain extension (i can't remember which one) interrupting the sizing of the previews.

**Comment by manisingh9** [comment]
i got many 50 around extensions which one to disable?
is it another twitch extension?

**Comment by MarkM-dev** [comment]
i don't remember which one, it might be something that is unrelated to twitch.

**Comment by manisingh9** [comment]
i got it, it is working now
it was twitch DVR player which was thwarting the slider to move.
