### ISSUE TITLE
Problem clip video twitch

### ISSUE THREAD

**Issue by Benzitczo** [MarkM-dev/Twitch-Previews#65]
When download "nimuVT.webm" and no cant upload video twitter here look image: https://prnt.sc/4sUiFbS4xk0W

translate: Your video file is not supported. See tips for uploading videos. - There problem "webm" but change is better mp4

**Comment by MarkM-dev** [comment]
The recorder is a very new browser feature and is not yet complete, we currently use webm to save the files and they are saved without metadata, when the browser vendors fix it, using the files more easily would be possible.
For now, if you want to upload the files to twitter you would need to convert them and then upload (use an online converter or a video editing software).
