### ISSUE TITLE
Screen shot on vods file name is broken

### ISSUE THREAD

**Issue by monicaellerose** [MarkM-dev/Twitch-Previews#66]
When taking a screenshot on  a vod, it just saves the file name as "png"  no name or period 
![image](https://user-images.githubusercontent.com/66647238/172601484-9eb5bae9-a131-4905-bc94-e90f34c1c7e1.png)

**Comment by MarkM-dev** [comment]
can you link an example vod where this is happening?

**Comment by monicaellerose** [comment]
any twitch highlight as example  this one from the official twitch page 
 https://www.twitch.tv/videos/1470539109  they save as png with no name 
![image](https://user-images.githubusercontent.com/66647238/173109506-93210489-80e5-495c-8b97-020235650648.png)

**Comment by MarkM-dev** [comment]
fixed for next version.
