### ISSUE TITLE
sidebar wrong settings to disable features

### ISSUE THREAD

**Issue by l4ejyetrgf** [MarkM-dev/Twitch-Previews#68]
Hovering over the sidebar for 3 seconds will show the picture-in-picture icon even though the setting "Multi-Stream & Multi-Chat" is disabled. Same with the "Drag & Drop streamers from the sidebar onto the page" Feature. Both is disabled if setting "Sidebar Previews" is disabled, but not if "Multi-Stream & Multi-Chat" is disabled

![0](https://user-images.githubusercontent.com/107694445/174307996-287fe564-aae4-4238-a8e2-25f6233cce43.png)

**Comment by MarkM-dev** [comment]
not exactly wrong setting, it's currently intentionally tied with the previews feature.
