### ISSUE TITLE
extend sidebar bugged?

### ISSUE THREAD

**Issue by toppits** [MarkM-dev/Twitch-Previews#7]
Maybe i understand the feature wrong, but i get the standard amount of items shown and the show more button.

I'm on latest chrome stable.

Enabled are directory preview, auto clicker and extended sidebar.

**Comment by MarkM-dev** [comment]
it's working here.. the feature should click the show more button to show all the LIVE streamers in the sidebar.
is it not extending until there is at least one offline streamer?

**Comment by toppits** [comment]
yea, nothing is happening. I can click like twice until the first offline.

But i also just remembered that i have bttv and ffz, and turning ffz off fixes the problem. Sorry.
