### ISSUE TITLE
[Feature request] m3u8 URL copy 

### ISSUE THREAD

**Issue by lunamoth** [MarkM-dev/Twitch-Previews#70]
Thanks for the extension. I have suggestions for adding features

It would be nice if there was a function to copy the m3u8 URL of the currently watched broadcast to the clipboard.

There are cases where I watch a broadcast with an m3u8 address with a pot player, but it would be convenient if I could copy the address right away.

Alternate Player for Twitch.tv (https://chrome.google.com/webstore/detail/alternate-player-for-twit/bhplkbgoehhhddaoolmakpocnenplmhf) extension is supported by right-clicking, so it would be good to refer to it.

**Comment by MarkM-dev** [comment]
Hi, doing that would require the webRequest permission.
that means that all traffic in your browser would also be received in the extension.
it's a scary permission and i don't want to add it just to get the m3u8 uri (which btw it's possible that twitch would change the m3u8 uri mid-stream).
However, i have been looking into options to start playing streams in external players so we can play games without the browser and twitch tab taking much ram and performance.

**Comment by lunamoth** [comment]
Thanks for the detailed explanation.

I understand why the feature cannot be supported

Thank you
