### ISSUE TITLE
New Twitch "Pin this channel" feature gets in the way

### ISSUE THREAD

**Issue by jaylay99** [MarkM-dev/Twitch-Previews#72]
![image](https://user-images.githubusercontent.com/76778450/180876223-26f35871-fecc-4f4c-87d9-f08459ea6f4c.png)

This extension's Favorite system is much better than Twitch's, so it'd be great if you could disable the Twitch's favorite system because the prompt can get annoying

**EDIT : I also just realized that it broke Twitch Previews "Video preview" feature. which is an even bigger deal.**

**Comment by Pixelz** [comment]
I got this as well. For now you can fix this with FFZ (if you have it)
in FFZ Control Center, go to Debugging -> Experiments.
Find "com30_pcln" in the list. Set it to "Control".
Maybe CTRL + F5 after that.
That should disable the pinning feature for now until someone develops a more permanent solution to fix the issues with it.

**Comment by MarkM-dev** [comment]
I noticed the video previews stopped working as-well, fixed the video previews in the sidebar and directories.
will be releasing a patch soon for the previews.

and ill see what's up with twitch's pinned channels feature and see what i can do.

**Comment by jaylay99** [comment]
> I got this as well. For now you can fix this with FFZ (if you have it) in FFZ Control Center, go to Debugging -> Experiments. Find "com30_pcln" in the list. Set it to "Control". Maybe CTRL + F5 after that. That should disable the pinning feature for now until someone develops a more permanent solution to fix the issues with it.

tyvm! that removed the Pin feature



> I noticed the video previews stopped working as-well, fixed the video previews in the sidebar and directories. will be releasing a patch soon for the previews.
> 
> and ill see what's up with twitch's pinned channels feature and see what i can do.

Thank you very much!!!

**Comment by MarkM-dev** [comment]
do you still have the pinned channels feature? or did they finish the testing?

**Comment by MarkM-dev** [comment]
All fixed, should work in any condition, made the pin/unpin button more friendly with the previews as-well. (v4.8).
