### ISSUE TITLE
content warning blocking video preview on sidebar // chrome 

### ISSUE THREAD

**Issue by jolnirw** [MarkM-dev/Twitch-Previews#73]
"The broadcaster has indicated that this channel is intended for mature audiences"
can't keep the window open to click "start watching"
will try reinstalling extension

**Comment by MarkM-dev** [comment]
no you have to go to the channel and approve it.
it's due to twitch's recent changes, the extension currently doesn't have the option to access the player layout.
ill see if i can make a fix when i can.

**Comment by jolnirw** [comment]
Even after approving via stream it still pops upSent from Samsung Mobile on O2
-------- Original message --------From: MarkM-dev ***@***.***> Date: 30/07/2022  9:42 pm  (GMT+00:00) To: MarkM-dev/Twitch-Previews ***@***.***> Cc: jolnirw ***@***.***>, Author ***@***.***> Subject: Re: [MarkM-dev/Twitch-Previews] content warning blocking video preview on sidebar // chrome  (Issue #73) 
no you have to go to the channel and approve it.
it's due to twitch's recent changes, the extension currently doesn't have the option to access the player layout.
ill see if i can make a fix when i can.

**Comment by MarkM-dev** [comment]
so here's the issue:
- twitch don't sync the "mature" flag in the local storage between their sub domains (www.twitch.tv and player.twitch.tv).
so if you click on "start watching" button on the mature content message on www.twitch.tv, it won't affect player.twitch.tv (which is the preview).
- You only need to click it once (unless you change computers or use incognito or somehow lose your browser's local storage for these domains).

Fix for now until i find a way to make this more user friendly:
when you encounter a preview with a mature content warning:
1. disable advanced video embeds (if you have it enabled).
2. open the streamer with the mature content in an embed (drag and drop the streamer from the sidebar onto the page or click the 4 squares button under the view count on the sidebar).
3. click the "start watching" button.
4. close the embed.
5. enable advanced video embeds (if you had it enabled).

**Comment by MarkM-dev** [comment]
the issue has been resolved. you will be able to click the button from the sidebar and the directory. a new version will be released in the next few days.
