### ISSUE TITLE
Recording feature broken?

### ISSUE THREAD

**Issue by tumba00** [MarkM-dev/Twitch-Previews#74]
Can you check if the Recording  feature is still working? when I stop and download the recording it's black for the duration it does capture the audio though

**Comment by MarkM-dev** [comment]
added a prompt to disable hardware acceleration. seems like a chromium issue, we'll have to wait for them to fix it.

**Comment by tumba00** [comment]
ok, i'll just use a seperate browser with acceleration off i hate turning it off on my main browser
