### ISSUE TITLE
tab preview dont work

### ISSUE THREAD

**Issue by carraira** [MarkM-dev/Twitch-Previews#75]
from one moment to another the sidebar previews do not show video, I have tried restarting the browser, reinstalling the extension, deleting cookies, but this function does not appear anymore. I Use Edge , Brave and Chrome but dont work.

Thank you

![image](https://user-images.githubusercontent.com/18118986/182997346-7e99456c-de5a-4319-bef5-62283c0cf129.png)

**Comment by MarkM-dev** [comment]
already fixed in 4.5 you should get the update very soon.
