### ISSUE TITLE
Sniper not placing votes on firefox.

### ISSUE THREAD

**Issue by LeetHaxor** [MarkM-dev/Twitch-Previews#8]
After the latest update (the one that changed the interface), the sniper doesn't work for me anymore. The preview sniper says it will vote, but when it comes time to vote, it just flickers (like it did before) to check the prediction, but never votes. I have my settings on 1% vote margin so every time it should be voting.

Edit: Further testing:
I even tried clicking Vote Now on the sniper screen which also did not work, it just flickers and doesn't vote. And also the sniper is showing as active with the green icon yet still not voting at the end.

**Comment by MarkM-dev** [comment]
it seems to be working here and in other clients, its possible that twitch changed the ui for some users.
can you see if it prints something to the console when it tries to vote?
if it does, it show be with the text "<date and time> APS:>  and then the reason under it.

**Comment by LeetHaxor** [comment]
[Here](https://i.imgur.com/eIwBDgw.png) is 2 from this morning

**Comment by MarkM-dev** [comment]
yep you're right, it's not working on firefox. ill look into it when i get a chance.

**Comment by LeetHaxor** [comment]
It seems to be working fine for me today. No errors in the console. I didn't change anything on my end as far as I know.

**Comment by MarkM-dev** [comment]
I uploaded a fix. it should roll out to users in the next few days (1.9.3.2 for Firefox).
I'm leaving this open for now, let me know if it's fixed for you when your extension gets the update.

**Comment by LeetHaxor** [comment]
Working fine now, even messed with settings a few times and tried voting early. Seems to be fixed, thanks!

**Comment by MarkM-dev** [comment]
Cool! thanks for letting me know about it.
