### ISSUE TITLE
Hovering a stream in the sidebar is missing volume button

### ISSUE THREAD

**Issue by Itamarbr** [MarkM-dev/Twitch-Previews#80]
![chrome_enKnxZZ0XP](https://user-images.githubusercontent.com/44429673/183617213-435fe80e-2a7e-4de9-8d1d-d8420df2beac.png)
The volume button that was usually there is gone since the Twitch change to pin channels

**Comment by MarkM-dev** [comment]
correct, twitch changed something and it is no longer available. i'm looking into ways to fix this in a proper way. might take a while until it can be re-enabled.

**Comment by MarkM-dev** [comment]
the issue has been resolved. added volume buttons to twitch and youtube sidebar features. a new version will be released in the next few days.
