### ISSUE TITLE
Request for a chat overlay feature

### ISSUE THREAD

**Issue by Switch123456789** [MarkM-dev/Twitch-Previews#81]
I am using [Anu Twitch Chat Overlay](https://chrome.google.com/webstore/detail/anu-twitch-chat-overlay/lfifccadmdnjffbbocnfmibmgddndbag) in combination with Twitch-Previews but it [seems incompatible](https://github.com/akhanubis/twitch_chat_overlay_issues/issues/40). Since the overlay-addon also is not open-source (not a fan), I thought maybe it could get added to this Twitch-Previews as an extra feature. yes?🙃please!

**Comment by MarkM-dev** [comment]
do you mean like the 'full screen with custom chat' feature that we have?
or the chat embed that you can customize (when mulstistream feature is on) which is the same as fullscreen with custom chat but available without the fullscreen part?

**Comment by Switch123456789** [comment]
Oh, yesterday when I tried all the features and clicked the button it only opened up the cinema-mode in fullscreen. I am not sure if it was buggy or I was just stupid, I guess the later. I am glad to see it is already included 👍 sorry for this unnecessary request. Great extension by the way!
