### ISSUE TITLE
Bug report: preview volume not working

### ISSUE THREAD

**Issue by Itamarbr** [MarkM-dev/Twitch-Previews#82]
Hey, thanks for bringing back the volume button on previews. There seems to be an issue now when you press the volume button the preview refreshes and nothing happens (no sound). In addition, scrolling up and down doesn't do anything

https://user-images.githubusercontent.com/44429673/185906674-1b635da3-00b0-4c5d-9038-d15b87d96b39.mp4

**Comment by MarkM-dev** [comment]
scrolling is no longer an option.
after clicking the volume button, move your cursor from the volume button to the preview window and change the volume. you probably set the volume on the embed (player.twitch.tv) to muted somewhere else that also uses twitch's same embeds url.
