### ISSUE TITLE
Can't go forward/backwards with arrow keys when a Twitch Extension is active

### ISSUE THREAD

**Issue by jaylay99** [MarkM-dev/Twitch-Previews#83]
I surprisingly use the left/right arrow a lot to go back seconds ago to watch something I missed, but unfortunately, when a Twitch extension is active, it won't let me do it. I have to disable any Twitch Extension to make the feature work. 

There are some Twitch Extensions that I really like so I don't want to actually disable them. That'd be great if that was fixed, thanks!

**Comment by MarkM-dev** [comment]
Hi,
it's not possible to catch events from twitch extensions elements because they don't bubble up from their iframes.
if you want to use the seek while extensions are over the video, click somewhere else on the page (not the video or a text input) and then seek.
