### ISSUE TITLE
Online Streamers are hidden from List

### ISSUE THREAD

**Issue by RedChiken** [MarkM-dev/Twitch-Previews#85]
Online Streamers are hidden from followed channel list.
Favorite listed are working normally. 
Just happen on followed channel list.

**Comment by RedChiken** [comment]
I Check other channels.
Issue occur on **some** channels
I don't know exactly condition to occur but some channel appear, some channel disappear.

**Comment by RedChiken** [comment]
OK I found when it occur.
When use favorite channels Options, almost 6 random online channels disappear from followed channel list.

**Comment by MarkM-dev** [comment]
check if you have "Hide favorite channels from followed list" enabled. if it is, disable it.
![image](https://user-images.githubusercontent.com/38380938/187699598-43a3487a-19b5-4f11-94b4-fefe3a229ab6.png)

**Comment by RedChiken** [comment]
I understand that option hide "favorite channels" from followed list.
But issue is Online channels are hidden from followed list even they are "not favorite channels".

**Comment by MarkM-dev** [comment]
are you sure this is because of twitch previews? try disabling twitch previews in the browser settings (or remove it) then refresh the page and see if it still happens.

**Comment by RedChiken** [comment]
Now I guarantee that it occur not because of other add-on.
I found that AdBlockPlus, Poper Blocker are activated.
And even I deactivated both of them, Issue still occur.

Need any information about my environment more?

**Comment by MarkM-dev** [comment]
yes:
1. go to the settings, and export your settings (bottom of the settings menu).
upload the file so i can see the settings.
2. what is your OS and browser versions?
3. if you could show me a video of it happening live that would be good.
4. do the streamers disappear from the sidebar right from the beginning of the page load or only when the favorites list starts to work (about 2 seconds after the page loads)?

**Comment by RedChiken** [comment]
It fixed after reinstall, but I leave options.
If you want to check this issues later, check it.

[Settings.txt](https://github.com/MarkM-dev/Twitch-Previews/files/9484881/Settings.txt)

1. I Upload Setting by txt because github not allow to upload json
2. Now I use v4.9.1
3. I Use Windows 10 and Chrome Ver 104.0.5112.102
![image](https://user-images.githubusercontent.com/7973257/188318967-7cc84080-1bb7-4280-9637-c9210f31a9e6.png)
4. It written in korea, so I explain it. On Main Page, Channels List started with LPL, nokduro, valorant_kr, kimdo, and ATK
But on followed channels list, LPL, nokduro, and valorant_kr is disappear.
5. It occur only when favorites list starts to work.

**Comment by MarkM-dev** [comment]
Thanks for letting me know about the issue.
i found what was causing it, it was the combination of these two settings:
![image](https://user-images.githubusercontent.com/38380938/188320416-ec9d8da2-65d2-4d3f-996f-cac134afba82.png)

fixed, a new version will be coming out tomorrow.
